Repository AY2425S2-CS2103-W11-2/tp, pull requests merged in 2025-03, with the labels that each got.

#15 Update AboutUs Page with Juraimi's Details
  docs/AboutUs.md
Labels: type.Task

#21 Update Developer Guide with product scope details
  docs/DeveloperGuide.md
Labels: type.Task

#19 Update Developer Guide with MVP User Stories
  docs/DeveloperGuide.md
Labels: type.Task

#27 Add remaining user stories to DG
  docs/DeveloperGuide.md
Labels: type.Task

#29 Add Use Case, NFR to DG
  docs/DeveloperGuide.md
Labels: type.Task

#32 docs: add use case NFR and glossary to DG
  docs/DeveloperGuide.md
Labels: type.Task

#34 Feature: edit delete command guide to be more specific
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Task

#42 Add basic search functionality
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Enhancement

#51 Fix Find Command Behaviour
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Bug

#53 Update UG for the Find Command
  docs/UserGuide.md
Labels: type.Task

#79 Enhance Find command functionality
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.Medium, severity.Low

#91 Add field to person class
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Importance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
Labels: type.Enhancement, priority.High

#92 Update UG with new Add/Edit Command Enhancements
  docs/UserGuide.md
Labels: type.Task, priority.High

#94 Fix Find functionality
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: type.Bug, priority.Medium

#98 Docs: update DG for add meeting command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#103 Fix Accepted Values for Importance Class
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Importance.java
Labels: type.Bug, priority.High, severity.High

#101 Enhance Sort Command with new Importance Field
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/SortComparator.java
Labels: type.Enhancement, type.Task, priority.High

#107 Docs: update model class diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#112 Update UML diagrams
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task
